# Generated by Django 3.2.14 on 2022-07-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbParkingDetailBlue',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('time', models.DateTimeField(blank=True, db_column='TIME', null=True)),
                ('s1', models.IntegerField(blank=True, null=True)),
                ('s2', models.IntegerField(blank=True, null=True)),
                ('s3', models.IntegerField(blank=True, null=True)),
                ('s4', models.IntegerField(blank=True, null=True)),
                ('s5', models.IntegerField(blank=True, null=True)),
                ('s6', models.IntegerField(blank=True, null=True)),
                ('s7', models.IntegerField(blank=True, null=True)),
                ('s8', models.IntegerField(blank=True, null=True)),
                ('s9', models.IntegerField(blank=True, null=True)),
                ('s10', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_parking_detail_blue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbParkingMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='NAME', max_length=45)),
                ('latitude', models.CharField(max_length=45)),
                ('longitude', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tb_parking_main',
                'managed': False,
            },
        ),
    ]
