# Generated by Django 3.2.14 on 2022-07-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_tbparkingdetailblue_tbparkingmain'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbParkingLog',
            fields=[
                ('time', models.DateTimeField(db_column='TIME', primary_key=True, serialize=False)),
                ('zone_id', models.CharField(db_column='ZONE_ID', max_length=45)),
                ('total_spots', models.CharField(blank=True, db_column='TOTAL_SPOTS', max_length=45, null=True)),
                ('equiped_spots', models.CharField(blank=True, db_column='EQUIPED_SPOTS', max_length=45, null=True)),
                ('equiped_spots_list', models.CharField(blank=True, db_column='EQUIPED_SPOTS_LIST', max_length=45, null=True)),
                ('empty_spots_list', models.CharField(blank=True, db_column='EMPTY_SPOTS_LIST', max_length=45, null=True)),
            ],
            options={
                'db_table': 'TB_PARKING_LOG',
                'managed': False,
            },
        ),
    ]
