# Generated by Django 3.2.14 on 2022-07-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_tbparkingmain_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbParkingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_id', models.CharField(blank=True, max_length=45, null=True)),
                ('normal_slots', models.CharField(blank=True, max_length=45, null=True)),
                ('special_slots', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'TB_PARKING_DETAIL',
                'managed': False,
            },
        ),
    ]
