# Generated by Django 3.2.14 on 2022-07-27 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_tbparkingdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='TbParkingDetailBlue',
        ),
    ]
