# Generated by Django 3.2.14 on 2022-08-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbParkingDetail',
            fields=[
                ('serial_id', models.CharField(db_column='SERIAL_ID', max_length=45, primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, db_column='ID', max_length=45, null=True)),
                ('totalspots', models.CharField(blank=True, db_column='TOTALSPOTS', max_length=45, null=True)),
                ('enable', models.IntegerField(blank=True, db_column='ENABLE', null=True)),
            ],
            options={
                'db_table': 'TB_PARKING_DETAIL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbParkingLog',
            fields=[
                ('time', models.DateTimeField(db_column='TIME', primary_key=True, serialize=False)),
                ('serial_id', models.CharField(db_column='SERIAL_ID', max_length=45)),
                ('enable', models.IntegerField(blank=True, db_column='ENABLE', null=True)),
                ('ocupiedlist', models.CharField(blank=True, db_column='OCUPIEDLIST', max_length=45, null=True)),
                ('total', models.IntegerField(blank=True, db_column='TOTAL', null=True)),
                ('enablelist', models.CharField(blank=True, db_column='ENABLELIST', max_length=45, null=True)),
            ],
            options={
                'db_table': 'TB_PARKING_LOG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbParkingMain',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=45, null=True)),
                ('latitude', models.CharField(blank=True, db_column='LATITUDE', max_length=45, null=True)),
                ('longitude', models.CharField(blank=True, db_column='LONGITUDE', max_length=45, null=True)),
                ('admin', models.CharField(blank=True, db_column='ADMIN', max_length=45, null=True)),
                ('owner', models.CharField(blank=True, db_column='OWNER', max_length=45, null=True)),
            ],
            options={
                'db_table': 'TB_PARKING_MAIN',
                'managed': False,
            },
        ),
    ]
