# Generated by Django 3.2.14 on 2022-07-25 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_tbparkinglog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbparkingmain',
            table='TB_PARKING_MAIN',
        ),
    ]
